[package]
authors = ["hubble459 <geraldd459@gmail.com>"]
edition = "2021"
name = "rumgap"
publish = false
version = "0.1.0"

[workspace]
members = [".", "entity", "migration", "parser"]

[dependencies]
log = "*"
env_logger = "*"
anyhow = "1"
argon2 = "0.4.1"
async-stream = {version = "^0.3"}
async-trait = "0.1.58"
entity = {path = "entity"}
futures = {version = "^0.3"}
futures-util = {version = "^0.3"}
hmac = "0.12.1"
jwt = "0.16.0"
migration = {path = "migration"}
parser = {path = "parser"}
rand_core = {version = "0.6", features = ["std"]}
rocket = {version = "0.5.0-rc.2", features = [
  "json",
]}
serde_json = {version = "^1"}
sha2 = "0.10.6"
chrono = "0.4"
regex = "1.7.0"

[dependencies.sea-orm-rocket]
git = "https://github.com/SeaQL/sea-orm"

[dependencies.sea-orm]
features = [
  "runtime-tokio-native-tls",
  "sqlx-mysql",
  "with-chrono",
]
version = "^0.10"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
