[package]
authors = ["hubble459 <geraldd459@gmail.com>"]
edition = "2021"
name = "rumgap"
publish = false
version = "0.1.0"

[workspace]
members = [".", "manga_parser", "migration", "entity"]

[dependencies]
actix-files = "0.6"
actix-web = "4"
manga-parser = {path = "manga_parser"}
migration = {path = "migration"}
entity = {path = "entity"}
log = "0"
env_logger = "0"
derive_more = "0.99"
argon2 = "0.4.1"
async-trait = "0.1.58"
lazy_static = "1"
futures = {version = "^0.3"}
futures-util = {version = "^0.3"}
hmac = "0.12.1"
jwt = "0.16.0"
sha2 = "0.10.6"
chrono = "0.4"
regex = "1.7.0"
dotenvy = "0.15"
listenfd = "1"
serde = { version = "1", features = ["derive"] }
sea-orm = { version = "0.10" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
