version: '3.8'
services:
  rumgap:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/rust_manga
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust_manga
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local