version: '3.8'
services:
  rumgap:
    build: .
    working_dir: /usr/local/bin
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      MANGA_UPDATE_INTERVAL_MS: 600000
      DATABASE_URL: "postgres://postgres:postgres@db/rust_manga"
      RUST_LOG: trace

    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    command: ["rumgap"]
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust_manga
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d rust_manga'"]
      interval: 2s
      timeout: 2s
      retries: 5
volumes:
  db:
    driver: local