worker_processes 1;

events {
	worker_connections 1024;
}

http {
	server {
		listen 8003;
		http2 on;
		server_name api.manga.quentincorreia.nl;

		location / {
			grpc_pass grpc://rumgap:8000;
		}
	}

	server {
		listen 5909 ssl;
		http2 on;
		server_name api.manga.quentincorreia.nl;

		ssl_certificate     /etc/nginx/certs/api.manga.quentincorreia.nl.pem;
		ssl_certificate_key /etc/nginx/certs/api.manga.quentincorreia.nl.key;

		location / {
			grpc_pass grpc://rumgap:8000;
		}
	}

	server {
		listen 8003;
		http2 on;
		server_name images.manga.quentincorreia.nl;

		location / {
			proxy_pass http://rumgap:8001;
		}
	}

	server {
		listen 8003;
		http2 on;
		server_name manga.quentincorreia.nl;

		location / {
			proxy_pass http://web:8080;
		}
	}
}
