name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    environment: main 
    runs-on: ubuntu-latest
    steps:
    - name: Install ProtoC & OpenSSL
      run: sudo apt-get install -y protobuf-compiler
    - uses: actions/checkout@main
    - name: Cache
      uses: actions/cache@v3.2.4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Add Toolchain
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --verbose --target x86_64-unknown-linux-musl
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "target/x86_64-unknown-linux-musl/rumgap"
        target: "Programs/rumgap"
