//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod canonical_chapter;
pub mod chapter;
pub mod chapter_image;
pub mod chapter_offset;
pub mod friend;
pub mod manga;
pub mod manga_source;
pub mod reading;
pub mod scrape_log;
pub mod user;
