//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

pub use super::chapter::Entity as Chapter;
pub use super::friend::Entity as Friend;
pub use super::manga::Entity as Manga;
pub use super::reading::Entity as Reading;
pub use super::user::Entity as User;
