//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reading")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub manga_id: i32,
    pub progress: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// Cached rank of the last-read canonical chapter, kept in sync with `progress`
    /// via one shared service function whenever either changes.
    pub last_canonical_chapter_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::manga::Entity",
        from = "Column::MangaId",
        to = "super::manga::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Manga,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::canonical_chapter::Entity",
        from = "Column::LastCanonicalChapterId",
        to = "super::canonical_chapter::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    CanonicalChapter,
}

impl Related<super::manga::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Manga.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::canonical_chapter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CanonicalChapter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
